# Generated by Django 5.0.6 on 2025-08-22 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("tool", models.CharField(max_length=32)),
                ("params", models.JSONField(default=dict)),
                ("estimate_tokens", models.IntegerField()),
                ("hold_tokens", models.IntegerField()),
                ("status", models.CharField(default="PENDING", max_length=16)),
                ("model_used", models.CharField(blank=True, max_length=64, null=True)),
                ("baseline_usd", models.FloatField(default=0)),
                ("retail_usd", models.FloatField(default=0)),
                ("breakdown", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActualUsage",
            fields=[
                (
                    "quote",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="usage",
                        serialize=False,
                        to="tokens.quote",
                    ),
                ),
                ("llm_in_1k", models.FloatField(default=0)),
                ("llm_out_1k", models.FloatField(default=0)),
                ("stt_min", models.FloatField(default=0)),
                ("tts_min", models.FloatField(default=0)),
                ("video_min", models.FloatField(default=0)),
                ("images_1024", models.IntegerField(default=0)),
                ("images_2048", models.IntegerField(default=0)),
                ("gpu_seconds", models.IntegerField(default=0)),
                ("meta", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("balance_tokens", models.IntegerField(default=0)),
                ("hold_tokens", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="quote",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tokens.wallet"
            ),
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("delta_tokens", models.IntegerField()),
                ("reason", models.CharField(max_length=64)),
                ("task_code", models.CharField(blank=True, max_length=64, null=True)),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger",
                        to="tokens.wallet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hold",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("tokens", models.IntegerField()),
                ("status", models.CharField(default="ACTIVE", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holds",
                        to="tokens.quote",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tokens.wallet"
                    ),
                ),
            ],
        ),
    ]
